sudo: false
language: node_js
deploy:
  api_key:
    secure: "YF18L6SCKorFMeg4VT1GU2eQrQOnuBkx7WPXGdCOk5MZxx0b6JDSKE5LT153dwrahfV21+tqnTNiV/V7/Hquz63M+xFbeB1tE9RWH407TM52/Ieob3IOhDpRR7OWwEWQE+An0JzNxfvXRiz7FXdtXGJcOm
    ltdDVsqr0uB7vpVJiG7I45BYrTcdyL5GOskRfXaBNceV83OLQNctOOZEtc7oHnU3M987MZtFkpv5ZXchV6Sr/TenAmaG9EbkYG6QB4Q4yaDuNzeuYSWJMiOfPEyYsVIpxApwS9UQKKpylHNncAur7BGrp8gErrRHJ7Fdl
    HMWgdDsw4kLuoc0JagQEwMbU4ut2/KZ0CWzOpomMytEztfwEh886lxFDezuzXwiPuB79K68K0IvIaAraDPpfyi0/RRqLGBR7aB6ntRl1btx87OpQPl/mcAqHTMB5I006qvgkJrekM+5OS6hze6NFVpS/P1x4QiRvSawex
    3/ZZgm3d7Z7Lb9MrxAtELLdm1Kb+gjFjCr3x2eT6AOaWbP0BNoO0i0ZyfnZXmY9EpyaYHtomy00vtk784Ix364OCmZax+IW8cY3NwmmfyPpv4QhoB3fBAT+Dql4QE0baA8cazHIgsKXeVQnTd0ZUMELGBXG2TZgPr6Vs6
    IVaNsGZINM1y8eGTJWcahV5R45/C9x5eJw="
 email: charles.jacuin@gmail.com
 provider: npm
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v5
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
